[package]
name = "render"
version = "0.2.0"
edition = "2018"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.13"
tera = "1.3.1"
lazy_static = "1.4.0"
url = "2.1.1"
anyhow = "1.0.31"
